hostname=leshiguang.com

^https:\/\/api-r7\.leshiguang\.com\/operation-rest\/api\/home\/v1\.0\/health\/scene\/hit\/query.* url script-response-body https://raw.githubusercontent.com/toaol/quanx_rewrite_scripts/refs/heads/master/Rewrite/LeiShiGuang.js
